Изменил состояния майнера
muska2203/power-of-war pull request #8
Opened 2019-09-29 17:51 UTC by gamezovladislav

1. Изменил состояния майнера. На данный момент они являются максимально атомарными.
2. Заменил отдельные числа-координаты единым объектом Point. 
Думаю, его надо оставить неизменяемым(как String в Java), потому что по конкретной точке строится вектор направления, а в случае изменяемости объектов Point могут происходить некая неразбериха и несоответствие данных в логике объектов.

2019-09-30 19:27 UTC, Romman requested changes

2019-10-01 15:31 UTC, muska2203 requested changes

2019-10-01 15:31 UTC, muska2203 commented on src/main/java/com/dreamteam/powerofwar/game/object/Miner.java
> -                    target = this.getNearestResource(board);
В методах `hetNearestResource` и `getNearestBase` стоит добавить фильтр, который отсеивает мертвые объекты.
Это исключит лишние переходы между состояниями и некоторые проверки.

2019-10-01 15:31 UTC, muska2203 commented on src/main/java/com/dreamteam/powerofwar/game/object/Miner.java
> +                target = getNearestBase(board);
В методе `getNearestBase` стоит переделать условие `!this.getOwner().isEnemyFor(gameObject.getOwner())` т.к. в игре планируется режим игры по командам. Стоит проверять на совпадение владельца базы и владельца добытчика.

2019-10-01 15:31 UTC, muska2203 commented on src/main/java/com/dreamteam/powerofwar/game/object/Miner.java
> +            case WAITING_FOR_RESOURCE:
Название состояния не соответствует поведению объекта. В данном состоянии он ищет ближайший ресурс, или ближайшую базу. 
Возможно стоит добавить состояние поиска базы.

2019-10-01 15:31 UTC, muska2203 commented on src/main/java/com/dreamteam/powerofwar/game/object/Miner.java
> +                if (this.isFull()) {
Здесь убирается вложенный if, если добавить дополнительное состояние. 
Описание в комментарии строки 48.

2023-06-15 19:14 UTC, closed without merging